### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by natanlao** [DataBiosphere/dos-azul-lambda#32]
```
(venv) natan@august ~/c/dos-azul-lambda (master)> nosetests
....FF
======================================================================
FAIL: Demonstrates basic paging features.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/natan/cgl/dos-azul-lambda/tests/test_app.py", line 110, in test_paging
    self.assertEquals(len(data_objects), 1)
AssertionError: 0 != 1

======================================================================
FAIL: Demonstrates how updating a Data Object should work to
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/natan/cgl/dos-azul-lambda/tests/test_app.py", line 147, in test_update
    self.assertEquals(get_response['statusCode'], 200)
AssertionError: 500 != 200

----------------------------------------------------------------------
Ran 6 tests in 0.372s

FAILED (failures=2)
```

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DAL-22)
┆Project Name: dos-azul-lambda
┆Issue Number: DAL-22

**Comment by david4096** [comment]
Try changing: https://github.com/DataBiosphere/dos-azul-lambda/blob/master/app.py#L189

```
        k = "{}.keyword".format(alias.split(":")[0])
```

That should enforce the uniqueness constraint.
